steps:
  # Install dependencies
  - name: 'node:22'
    entrypoint: npm
    args: ['install']

  # Build the Next.js application
  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
